services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
      # Example: Pass build arguments from a .env file (uncomment if you have a .env and Dockerfile ARGs)
      # args:
      #   - VITE_API_KEY=${VITE_API_KEY}
      #   - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      #   - VITE_OLLAMA_BASE_URL=${VITE_OLLAMA_BASE_URL:-http://ollama:11434} # Default to service name
      #   - VITE_OLLAMA_MODEL_NAME=${VITE_OLLAMA_MODEL_NAME:-llama3}
    env_file:
      - .env
    # Uncomment the following lines if you want to pass environment variables directly
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080


  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 3 && ollama pull qwen:0.5b && wait"]


volumes:
  ollama_data:

